version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: src/back/Dockerfile
    container_name: hyundai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build:
      context: .
      dockerfile: src/front/Dockerfile
    container_name: hyundai-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
